// generated by vitest-vue2-init — sample component test
//
// This file proves: @vitejs/plugin-vue2 compiles SFCs, @vue/test-utils mount works,
// global mocks in setup.ts cover the zz-ui surface.

import { describe, it, expect } from 'vitest'
import Vue from 'vue'
import { mount } from '@vue/test-utils'

// Inline SFC defined as an object — replace with a real import once a target component exists.
const SampleComponent = Vue.extend({
  props: {
    greeting: { type: String, default: 'Hello' },
    name: { type: String, required: true }
  },
  template: '<div class="sample">{{ greeting }} {{ name }}</div>'
})

describe('sample component test', () => {
  it('renders the greeting and name', () => {
    const wrapper = mount(SampleComponent, { propsData: { name: 'World' } })
    expect(wrapper.text()).toBe('Hello World')
  })

  it('respects custom greeting prop', () => {
    const wrapper = mount(SampleComponent, { propsData: { greeting: 'Hi', name: 'Alice' } })
    expect(wrapper.text()).toBe('Hi Alice')
  })
})
