// generated by vitest-vue2-init — sample utility test for smoke-validating the setup
//
// This file proves: vitest can run, TS is transpiled, basic imports work.
// Replace this with real tests once the framework is validated.

import { describe, it, expect } from 'vitest'

// Example pure function under test — replace with a real one from src/utils/
function fen2yuan(fen: number): number {
  return fen / 100
}

describe('sample utility test', () => {
  it('fen2yuan converts cents to yuan', () => {
    expect(fen2yuan(199900)).toBe(1999)
  })

  it('handles zero', () => {
    expect(fen2yuan(0)).toBe(0)
  })
})
