// Main-line setup.ts template — vue 2.7 + composition + pinia
//
// Generated by vitest-vue2-init skill.
// For test authoring conventions after this is in place, see skill: vitest-vue2-testing.
//
// What this file does:
//   1. Mocks third-party SDKs that have remote-script side effects (lego/native-adapter/zz-utils/zz-ui/zz-fetch/lottie-web)
//   2. Installs Vue prototype helpers commonly used in templates ($setPicSize)
//   3. Polyfills browser APIs missing in happy-dom (matchMedia)
//
// CONDITIONAL ADDITIONS (uncomment based on stack profile from detect-stack.mjs):
//   • Vue 2.6 + @vue/composition-api:  import VueCompositionAPI from '@vue/composition-api'; Vue.use(VueCompositionAPI)
//   • Vuex:                            import Vuex from 'vuex'; Vue.use(Vuex)
//   • Additional private deps:         see references/private-deps-mock-catalog.md
//
// MOCK COMPLETENESS PRINCIPLE:
//   Every vi.mock factory must export every named symbol production code accesses.
//   To audit: grep -rh "from ['\"]<pkg>['\"]" src | grep -oE "\{[^}]+\}" | tr -d "{}" | tr ',' '\n' | sort -u

import { vi } from 'vitest'
import Vue from 'vue'

// 1. lottie-web — many @zz-common/zz-ui components depend on it
vi.mock('lottie-web', () => ({
  default: {
    loadAnimation: vi.fn(() => ({
      destroy: vi.fn(), play: vi.fn(), stop: vi.fn(), pause: vi.fn(),
      goToAndPlay: vi.fn(), goToAndStop: vi.fn(),
      addEventListener: vi.fn(), removeEventListener: vi.fn()
    }))
  }
}))

// 2. @zz-common/zz-ui — Vue.extend stubs MUST use a factory function;
//    sharing one options object causes Vue.extend to mutate props on first call,
//    breaking subsequent spreads ("props is not iterable").
vi.mock('@zz-common/zz-ui', () => {
  const makeStub = () => ({
    template: '<div class="zz-stub"><slot /></div>',
    props: ['index', 'indexList', 'sticky', 'scrollDom', 'forceAdaptIndexListAnchor',
      'position', 'zIndex', 'customClass', 'text', 'info', 'type', 'keepPosition',
      'enableFadeIn', 'headerTaskbarBG', 'name', 'classPrefix', 'cancelText',
      'modelValue', 'className'],
    methods: { $emit: vi.fn() }
  })
  const stub = () => Vue.extend(makeStub())

  // Imperative services must be functions + static methods
  const toastFn: any = vi.fn()
  toastFn.success = vi.fn(); toastFn.fail = vi.fn(); toastFn.loading = vi.fn(); toastFn.clear = vi.fn()
  const dialogFn: any = vi.fn(() => Promise.resolve())
  dialogFn.confirm = vi.fn(() => Promise.resolve())
  dialogFn.alert = vi.fn(() => Promise.resolve())
  dialogFn.close = vi.fn()

  return {
    default: stub(),
    Toast: toastFn, Dialog: dialogFn, Notify: vi.fn(), ImagePreview: vi.fn(),
    IndexBar: stub(), IndexAnchor: stub(),
    Popup: Vue.extend({ ...makeStub(), props: [...makeStub().props, 'position', 'zIndex'] }),
    Actionsheet: stub(), FixTop: stub(), Icon: stub(), Info: stub(), FloatBtn: stub(),
    Button: stub(), ButtonGroup: stub(), NavBar: stub(),
    Tabs: stub(), Tab: stub(), PullRefresh: stub(), List: stub(),
    ActionPicker: stub(), Picker: stub(), Stance: stub(),
    Field: stub(), Cell: stub(), CellGroup: stub(),
    Checkbox: stub(), CheckboxGroup: stub(), Radio: stub(), RadioGroup: stub(),
    Switch: stub(), Tag: stub(), Image: stub(),
    Loading: stub(), Overlay: stub(), Sticky: stub(),
    Swipe: stub(), SwipeItem: stub(),
    __esModule: true
  }
})

// 3. @zz-common/native-adapter — src/utils/env.ts calls getClient() and in() at module load;
//    missing either crashes tests that transitively import env.ts.
vi.mock('@zz-common/native-adapter', () => {
  const native = {
    isLogin: vi.fn(() => false),
    close: vi.fn(),
    skipToUrl: vi.fn(),
    getClient: vi.fn(() => 'zhuanzhuan'),
    in: vi.fn(() => false)
  }
  return { default: native, ...native }
})

// 4. @zz-common/zz-utils — helper.ts uses cookie.get; env.ts uses url.getParams()
vi.mock('@zz-common/zz-utils', () => ({
  setPicSize: (url: string, _size?: number) => url,
  getCookie: vi.fn(),
  cookie: { get: vi.fn(() => ''), set: vi.fn(), remove: vi.fn() },
  url: {
    getParams: vi.fn(() => ({})),
    getQuery: vi.fn(() => ({})),
    parse: vi.fn(() => ({})),
    stringify: vi.fn(() => '')
  },
  env: { isZZ: false, isZZB: false, isApp: false, isAndroid: false, isIOS: false }
}))

// 5. @zz-common/lego — cover all named exports production code imports
vi.mock('@zz-common/lego', () => {
  const noop = vi.fn()
  return {
    lego: { send: noop, sendNew: noop, resumePV: noop },
    legoInit: { setUserBackup: noop, resumePV: noop, init: noop, setExtraInfo: noop },
    legoPerf: { send: noop, mark: noop, measure: noop },
    legoReport: noop,
    legoGoodsExposure: noop,
    legoAreaExposure: noop,
    legoZPMExposure: noop,
    pageId: vi.fn(() => '')
  }
})

// 6. @zz/fetch — neutralize JSONP whitelist init that hits the network at module load
vi.mock('@zz/fetch', () => {
  const okResp = { respCode: 0, respData: {} }
  return {
    default: vi.fn(() => Promise.resolve(okResp)),
    get: vi.fn(() => Promise.resolve(okResp)),
    post: vi.fn(() => Promise.resolve(okResp)),
    jsonp: vi.fn(() => Promise.resolve(okResp))
  }
})

// 7. Vue prototype helpers consumed inside templates
;(Vue.prototype as any).$setPicSize = (src: string, _size?: number) => src

// 8. happy-dom polyfills
if (!(globalThis as any).matchMedia) {
  ;(globalThis as any).matchMedia = vi.fn().mockReturnValue({
    matches: false,
    media: '',
    onchange: null,
    addListener: vi.fn(),
    removeListener: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    dispatchEvent: vi.fn()
  })
}
