// Main-line vitest config template — vue 2.7 + composition + pinia (+ optional plugins)
//
// Generated by vitest-vue2-init skill.
// For test authoring conventions after this is in place, see skill: vitest-vue2-testing.
//
// Conditional additions (uncomment as needed; see references in vitest-vue2-init/):
//   • TSX/JSX:   import vueJsx from '@vitejs/plugin-vue2-jsx'  →  plugins: [vue(), vueJsx()]
//   • Class:     vue({ babel: { plugins: [['@babel/plugin-proposal-decorators', { legacy: true }]] } })
//   • Heavy SDK side-effect noise: test.server.deps.inline (see cdn-and-async-noise.md)

import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue2'

export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      '@': new URL('./src', import.meta.url).pathname
    }
  },
  test: {
    environment: 'happy-dom',
    include: ['tests/unit/**/*.{test,spec}.{ts,tsx,js,jsx}'],
    setupFiles: ['./tests/unit/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      include: ['src/**/*.{ts,js,vue}'],
      exclude: ['src/**/*.d.ts', 'src/main.ts', 'src/App.vue']
    }
  }
})
